package ui

import (
	"encoding/json"
	"net/http"
	"os"
	"path/filepath"

	"github.com/wpg/wpgctl/internal/config"
	"gopkg.in/yaml.v3"
)

// handleSiteForm 接收结构化表单字段，生成并校验 site.yaml。
func (s *Server) handleSiteForm(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPut && r.Method != http.MethodPost {
		http.Error(w, "method not allowed", 405)
		return
	}
	var body config.SiteConfig
	if err := json.NewDecoder(r.Body).Decode(&body); err != nil {
		s.writeJSON(w, 400, map[string]string{"error": "表单解析失败: " + err.Error()})
		return
	}
	// 空密码保留原文件值，避免脱敏回显导致误清空
	if existing, err := config.LoadSite(s.opts.SitePath); err == nil {
		if body.Middleware.Nacos.Password == "" {
			body.Middleware.Nacos.Password = existing.Middleware.Nacos.Password
		}
		if body.Middleware.MySQL.Password == "" {
			body.Middleware.MySQL.Password = existing.Middleware.MySQL.Password
		}
		if body.Middleware.Redis.Password == "" {
			body.Middleware.Redis.Password = existing.Middleware.Redis.Password
		}
		if body.Middleware.PgSQL.Password == "" {
			body.Middleware.PgSQL.Password = existing.Middleware.PgSQL.Password
		}
	}
	// 默认 SSH 端口
	for i := range body.Nodes {
		if body.Nodes[i].SSH.Port == 0 {
			body.Nodes[i].SSH.Port = 22
		}
		if body.Nodes[i].SSH.User == "" {
			body.Nodes[i].SSH.User = "root"
		}
	}
	body.Normalize()
	if err := body.Validate(); err != nil {
		s.writeJSON(w, 400, map[string]string{"error": err.Error()})
		return
	}
	data, err := yaml.Marshal(&body)
	if err != nil {
		s.writeJSON(w, 500, map[string]string{"error": err.Error()})
		return
	}
	header := []byte("# generated by wpgctl ui form — 也可用 YAML 高级模式编辑\n")
	out := append(header, data...)
	dir := filepath.Dir(s.opts.SitePath)
	_ = os.MkdirAll(dir, 0o755)
	tmp := s.opts.SitePath + ".tmp"
	if err := os.WriteFile(tmp, out, 0o644); err != nil {
		s.writeJSON(w, 500, map[string]string{"error": err.Error()})
		return
	}
	if _, err := config.LoadSite(tmp); err != nil {
		_ = os.Remove(tmp)
		s.writeJSON(w, 400, map[string]string{"error": "校验失败: " + err.Error()})
		return
	}
	if err := os.Rename(tmp, s.opts.SitePath); err != nil {
		if err2 := os.WriteFile(s.opts.SitePath, out, 0o644); err2 != nil {
			s.writeJSON(w, 500, map[string]string{"error": err2.Error()})
			return
		}
		_ = os.Remove(tmp)
	}
	s.writeJSON(w, 200, map[string]any{"ok": true, "path": s.opts.SitePath, "site": body.Site})
}
